### ISSUE TITLE
Bug: Require cycles are allowed, but can  ....

### ISSUE THREAD

**Issue by lvlrSajjad** [fnando/i18n-js#657] opened 2022-08-02 07:33 UTC
## Description

I use this library in my react-native project.
After upgrading to 4.0.2 I get these warning.

```
 WARN  Require cycle: node_modules/i18n-js/dist/import/helpers/index.js -> node_modules/i18n-js/dist/import/helpers/numberToHumanSize.js -> node_modules/i18n-js/dist/import/helpers/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/i18n-js/dist/import/helpers/index.js -> node_modules/i18n-js/dist/import/helpers/pluralize.js -> node_modules/i18n-js/dist/import/helpers/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/i18n-js/dist/import/helpers/index.js -> node_modules/i18n-js/dist/import/helpers/roundNumber.js -> node_modules/i18n-js/dist/import/helpers/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules/i18n-js/dist/import/helpers/index.js -> node_modules/i18n-js/dist/import/helpers/timeAgoInWords.js -> node_modules/i18n-js/dist/import/helpers/index.js

```
## How to reproduce

install version 4.0.2 and use it this way:

```es6
import * as Localization from "expo-localization"
import { I18n } from "i18n-js"
import en from "./en_us.json"
import es from "./es_mx.json"
import fr from "./fr_ca.json"

export const i18n = new I18n({ en, es, fr }, {
  enableFallback: true,
  defaultLocale: Localization.locale || "en"
});

export const switchLocale = (code: string) => {
  i18n.locale = code
}
```

**Comment by fnando** [comment] 2022-08-03 19:45
Hi, @lvlrSajjad. Can you please upload a sample app reproducing this issue? Thanks!

**Comment by fnando** [comment] 2022-08-03 20:32
Hey! I couldn't reproduce these warnings. Here's the app I tried: [foo.zip](https://github.com/fnando/i18n-js/files/9254865/foo.zip)

Can you please give it a try and let me know if it seems okay? The only different is that I didn't import expo-localization.

**Comment by codeion** [comment] 2022-08-22 07:36
Warnings are there, you can quickly check it with [metro-plugin-cyclic-dependencies-detector](https://microsoft.github.io/rnx-kit/docs/tools/metro-plugin-cyclic-dependencies-detector)

warn i18n-js/dist/import/helpers/index.js
warn └── i18n-js/dist/import/helpers/timeAgoInWords.js
warn     └── i18n-js/dist/import/helpers/index.js
warn         └── i18n-js/dist/import/MissingTranslation.js

**Comment by fnando** [comment] 2022-12-09 22:08
I believe this issue has been fixed by https://github.com/fnando/i18n/pull/35.

Can you please try the latest version and see if fixes it? I'll close this issue for now.

**Closed by fnando** 2022-12-09 22:08 UTC
