### ISSUE TITLE
Modular structure

### ISSUE THREAD

**Issue by stgeneral** [fnando/i18n-js#289] opened 2014-12-25 14:13 UTC
While i18n-js is very lightweight it would be even better to be modular.

For example there several function for date & time: `I18n.parseDate`, `I18n.strftime`, `I18n.toTime` which may be used not in every project or be replaced with some other libs (like moment.js).

As well as other functions like `I18n.toHumanSize` or `I18n.toHumanSize` may not be used in every project.

So, it would be good to have `i18n-core` in a separate file and helpers/extensions in other files in order we could include only that modules that really used in the project.

Thank you for the great gem!

**Comment by johnnyshields** [comment] 2015-01-05 16:12
This is a dupe of https://github.com/fnando/i18n-js/issues/163 which was closed, however, I still agree with the viewpoint that the JS should be made more modular.

**Comment by PikachuEXE** [comment] 2015-01-06 01:27
This needs to wait for 4.0 at least :S

**Comment by johnnyshields** [comment] 2015-01-06 11:26
One way to achieve this would be to use ECMAScript 6 modules, and then transpile-them to the built JS file. This might be overkill considering (at least in the current code) all modules would extend `I18n` in the global namespace.

**Comment by dmitry** [comment] 2015-07-30 10:53
I'm also joining into the discussion to make a i18n-js more modular, release it as a npm package, and make it able to bundle with webpack. Personally I'm using it in node.js (and react), but have some ruby projects too.

**Comment by johnnyshields** [comment] 2015-07-30 11:16
@dmitry 100% agree, think that's a great idea.

**Comment by fnando** [comment] 2016-03-19 04:15
This library is ~3.4kb gzipped. Breaking functions into separate modules will make things harder (e.g. we'll have to introduce some compilation step to support ES6 and whatnot), without a real benefit. The only missing thing is exporting vanilla versions that can be easily bundled with your preferred tool (webpack, browserify, etc).

I'm working on something that will allow using i18n-js with Rails + ES6 modules and you'll be able to import what you need (although the whole lib will be loaded, but still ~3.4kb). This already works:

```js
import { t, toNumber } from 'i18n';
```

I'm planning to push my work soon. :)

**Closed by fnando** 2016-03-19 04:15 UTC

**Comment by johnnyshields** [comment] 2016-03-19 16:46
@fnando I think we should separate the JS and Ruby components of this lib into separate repos, and distribute the JS via NPM. I'm using just the JS in a pure JS app.

**Comment by fnando** [comment] 2016-03-19 16:50
@johnnyshields we can distribute this repo as a NPM package. Just need to tweak .npmignore and package.json's files node, serving static files from `dist`.

What if I say that I already have this in place? I'll push my idea of a newer I18n.js later today. :)

**Comment by johnnyshields** [comment] 2016-03-19 16:53
:+1: nice!! Let's do it.

**Comment by fnando** [comment] 2016-03-19 23:52
@johnnyshields I'd appreciate your input on #399. :)
