### ISSUE TITLE
I18n::JS::Middleware autogeneration not working in Rails 4.2.3

### ISSUE THREAD

**Issue by seoyoochan** [fnando/i18n-js#350] opened 2015-08-04 15:42 UTC
I added `config.middleware.use I18n::JS::Middleware` in `development.rb`
but it does not work in rails 4.2.3
can someone reproduce this?

**Comment by PikachuEXE** [comment] 2015-08-05 08:03
Please provide more info first
such as versions of common gems like `rails` and `sprockets`

Describe what is expected and what actually happens

**Comment by alvinsj** [comment] 2015-12-03 09:04
@seoyoochan @PikachuEXE I have similar issue with the use of config/i18n-js.yml.
This is how I reproduce:

In `config/i18n-js.yml`:
```yaml
translations:
  - file: "public/javascripts/i18n/a.translations.js"
    only: ["*.a"]
  - file: "public/javascripts/i18n/b.translations.js"
    only: ["*.b"]
```
0. At first, everything is working. 
1. Remove what is in `public/javascripts/i18n/`
2. Refresh the app, and see `missing translations` error.
3. Remove `tmp/cache/i18n-js.yml`
4. Refresh the app again, It works now by newly generated files as specified in `config/i18n-js.yml`

**Comment by PikachuEXE** [comment] 2015-12-03 09:25
I guess the file is not checking whether the files exists or not.
I will change it later to accept additional options.

Thanks for providing the info. Middleware are hard to test (for me)

**Comment by ezuk** [comment] 2016-03-03 18:08
I just want to say that for me, this is not fixed. I just had to manually remove `tmp/cache/i18n-js.yml` to get it to work in dev mode.

**Comment by PikachuEXE** [comment] 2016-03-03 23:58
I plan to "fix" it before 3.0.0, but it might be be soon
If anyone are having this problem and able to fix it, please submit a PR so that other people with the same issue can test that :)

**Comment by tleish** [comment] 2016-04-13 04:56
It makes sense to me that the middleware cache would be cleared each time Rails starts.  I think checking to see if all the file still exists is the wrong approach because approach because which every page request you are parsing all the locale yaml files in order to get possible exported file names which would slow down each request.

If others feel they want the middleware to resolve with each page request, I think there should be a separate config setting in the 18n-js.yml.  Something like:

```yaml
ignore_middleware_cache: true
```

Again, I think this is the wrong approach and I've added a pull request for the approach that I think it the best strategy.

**Comment by PikachuEXE** [comment] 2016-04-13 05:00
@tleish 
Thanks for the PR
I just want to make sure no one is using that thing in production (or other places where performance is considered important)
Otherwise that caching can be removed (until a bug-less caching can be implemented)

**Comment by tleish** [comment] 2016-04-13 05:26
I'm not following why this would be an issue in production.  This isn't removing caching in the middleware, it's only resets the caching once after the rails starts.  Otherwise after the cache is created, each subsequent request (page refresh) uses the cache from then on.  This mimics the same behavior of rails in that it initially loads and caches the yaml files into memory when the application first starts, and then uses the cache from then on.

With my pull request, if someone is using the middleware in production then this would only impact the very first request where it would rebuild the cache and files.  Otherwise, it would continue to use the cache until someone restarts rails, which in production usually means a new deployment.

In the meantime, I've added this to my rails configuration which does the same thing.

```ruby
I18N_MIDDLEWARE_CACHE = 'tmp/cache/i18n-js.yml'
if Rails.env.development? && File.exist?(I18N_MIDDLEWARE_CACHE)
    File.delete(I18N_MIDDLEWARE_CACHE) # clear i18n-js cache on startup
    config.middleware.use(I18n::JS::Middleware)
end
```

**Comment by PikachuEXE** [comment] 2016-04-13 05:28
My bad
mistaken `#call` with `#initialize`
I need clean my eyes :)

**Comment by afdev82** [comment] 2018-11-27 12:06
Is it fixed? For me it doesn't work on Rails 5.2 too, this is my `Gemfile.lock`:

```
GIT
  remote: https://github.com/adnotam/alchemy-pg_search.git
  revision: 2ffa210aba81f1d4a3581e3dd1cf4b1bc4c473a3
  branch: custom
  specs:
    alchemy-pg_search (1.1.0)
      alchemy_cms (> 3.2, < 5.0)
      pg
      pg_search (~> 0.7)

GIT
  remote: https://github.com/adnotam/alchemy_cms.git
  revision: c5cf9ba4f76b64eb245f5fe36660dd3bcbef60e1
  branch: custom
  specs:
    alchemy_cms (4.1.0)
      active_model_serializers (~> 0.9.0)
      acts_as_list (~> 0.3)
      awesome_nested_set (~> 3.1)
      cancancan (~> 2.1)
      coffee-rails (~> 4.0)
      dragonfly (~> 1.0, >= 1.0.7)
      dragonfly_svg (~> 0.0.4)
      gutentag (~> 2.2, >= 2.2.1)
      handlebars_assets (~> 0.23)
      jquery-rails (~> 4.0, >= 4.0.4)
      jquery-ui-rails (~> 6.0)
      kaminari (~> 1.1)
      non-stupid-digest-assets (~> 1.0.8)
      originator (~> 3.1)
      rails (~> 5.0, < 6.0)
      ransack (~> 2.0)
      request_store (~> 1.2)
      responders (~> 2.0)
      select2-rails (>= 3.5.9.1, < 4.0)
      simple_form (~> 4.0)
      turbolinks (>= 2.5)

GIT
  remote: https://github.com/adnotam/wice_grid.git
  revision: f85f2938f08bdfca158401ad5b08bfcdf254b054
  branch: custom
  specs:
    wice_grid (4.0.1)
      coffee-rails (> 3.2)
      kaminari (~> 1.1.0)
      rails (~> 5.0, < 5.3)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.2.1)
      actionpack (= 5.2.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailer (5.2.1)
      actionpack (= 5.2.1)
      actionview (= 5.2.1)
      activejob (= 5.2.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.2.1)
      actionview (= 5.2.1)
      activesupport (= 5.2.1)
      rack (~> 2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.2.1)
      activesupport (= 5.2.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    active_model_serializers (0.9.7)
      activemodel (>= 3.2)
      concurrent-ruby (~> 1.0)
    activejob (5.2.1)
      activesupport (= 5.2.1)
      globalid (>= 0.3.6)
    activemodel (5.2.1)
      activesupport (= 5.2.1)
    activerecord (5.2.1)
      activemodel (= 5.2.1)
      activesupport (= 5.2.1)
      arel (>= 9.0)
    activerecord-session_store (1.1.1)
      actionpack (>= 4.0)
      activerecord (>= 4.0)
      multi_json (~> 1.11, >= 1.11.2)
      rack (>= 1.5.2, < 3)
      railties (>= 4.0)
    activestorage (5.2.1)
      actionpack (= 5.2.1)
      activerecord (= 5.2.1)
      marcel (~> 0.3.1)
    activesupport (5.2.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    acts_as_list (0.9.17)
      activerecord (>= 3.0)
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    ahoy_email (1.0.2)
      actionmailer (>= 4.2)
      addressable (>= 2.3.2)
      nokogiri
      safely_block (>= 0.1.1)
    ahoy_matey (2.1.0)
      addressable
      browser (~> 2.0)
      device_detector
      geocoder (>= 1.4.5)
      railties (>= 4.2)
      referer-parser (>= 0.3)
      request_store
      safely_block (>= 0.2.1)
      user_agent_parser
    airbrussh (1.3.1)
      sshkit (>= 1.6.1, != 1.7.0)
    arel (9.0.0)
    ast (2.4.0)
    autoprefixer-rails (9.3.1)
      execjs
    awesome_nested_set (3.1.4)
      activerecord (>= 4.0.0, < 5.3)
    base58 (0.2.3)
    bcrypt (3.1.12)
    bindex (0.5.0)
    brakeman (4.3.1)
    browser (2.5.3)
    builder (3.2.3)
    bullet (5.9.0)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.11)
    byebug (10.0.2)
    cancancan (2.3.0)
    capistrano (3.11.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-bundler (1.4.0)
      capistrano (~> 3.1)
      sshkit (~> 1.2)
    capistrano-rails (1.4.0)
      capistrano (~> 3.1)
      capistrano-bundler (~> 1.1)
    capistrano-rbenv (2.1.4)
      capistrano (~> 3.1)
      sshkit (~> 1.3)
    capistrano-yarn (2.0.2)
      capistrano (~> 3.0)
    capistrano3-puma (3.1.1)
      capistrano (~> 3.7)
      capistrano-bundler
      puma (~> 3.4)
    capybara (3.11.1)
      addressable
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (~> 1.2)
      xpath (~> 3.2)
    capybara-screenshot (1.0.22)
      capybara (>= 1.0, < 4)
      launchy
    childprocess (0.9.0)
      ffi (~> 1.0, >= 1.0.11)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.1.3)
    countries (2.1.4)
      i18n_data (~> 0.8.0)
      money (~> 6.9)
      sixarm_ruby_unaccent (~> 1.1)
      unicode_utils (~> 1.4)
    crack (0.4.3)
      safe_yaml (~> 1.0.0)
    crass (1.0.4)
    css_parser (1.6.0)
      addressable
    dalli (2.7.9)
    device_detector (1.0.1)
    devise (4.5.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 6.0)
      responders
      warden (~> 1.2.3)
    devise-i18n (1.7.0)
      devise (>= 4.5)
    diff-lcs (1.3)
    docile (1.3.1)
    domain_name (0.5.20180417)
      unf (>= 0.0.5, < 1.0.0)
    dragonfly (1.2.0)
      addressable (~> 2.3)
      multi_json (~> 1.0)
      rack (>= 1.3)
    dragonfly_svg (0.0.4)
      dragonfly (~> 1.0)
      nokogiri
    errbase (0.1.1)
    erubi (1.7.1)
    execjs (2.7.0)
    factory_bot (4.11.1)
      activesupport (>= 3.0.0)
    factory_bot_rails (4.11.1)
      factory_bot (~> 4.11.1)
      railties (>= 3.0.0)
    faker (1.9.1)
      i18n (>= 0.7)
    faraday (0.15.3)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.25)
    foundation_emails (2.2.1.0)
    geocoder (1.5.0)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    gutentag (2.4.0)
      activerecord (>= 3.2.0)
    handlebars_assets (0.23.2)
      execjs (~> 2.0)
      sprockets (>= 2.0.0)
      tilt (>= 1.2)
    hashdiff (0.3.7)
    hashie (3.5.7)
    highline (2.0.0)
    htmlentities (4.3.4)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    i18n (1.1.1)
      concurrent-ruby (~> 1.0)
    i18n-js (3.2.0)
      i18n (>= 0.8.0, < 2)
    i18n-tasks (0.9.28)
      activesupport (>= 4.0.2)
      ast (>= 2.1.0)
      erubi
      highline (>= 2.0.0)
      i18n
      parser (>= 2.2.3.0)
      rails-i18n
      rainbow (>= 2.2.2, < 4.0)
      terminal-table (>= 1.5.1)
    i18n_data (0.8.0)
    iniparse (1.4.4)
    inky-rb (1.3.7.3)
      foundation_emails (~> 2)
      nokogiri
    inline_svg (1.3.1)
      activesupport (>= 3.0)
      nokogiri (>= 1.6)
    jaro_winkler (1.5.1)
    jbuilder (2.8.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jquery-rails (4.3.3)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (6.0.1)
      railties (>= 3.2.16)
    json (2.1.0)
    jwt (2.1.0)
    kaminari (1.1.1)
      activesupport (>= 4.1.0)
      kaminari-actionview (= 1.1.1)
      kaminari-activerecord (= 1.1.1)
      kaminari-core (= 1.1.1)
    kaminari-actionview (1.1.1)
      actionview
      kaminari-core (= 1.1.1)
    kaminari-activerecord (1.1.1)
      activerecord
      kaminari-core (= 1.1.1)
    kaminari-core (1.1.1)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.6.0)
      launchy (~> 2.2)
    libv8 (6.7.288.46.1)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.2.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (0.3.3)
      mimemagic (~> 0.3.2)
    maxminddb (0.1.22)
    method_source (0.9.2)
    mime-types (3.2.2)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2018.0812)
    mimemagic (0.3.2)
    mini_mime (1.0.1)
    mini_portile (0.6.2)
    mini_portile2 (2.3.0)
    mini_racer (0.2.4)
      libv8 (>= 6.3)
    minitest (5.11.3)
    monetize (1.9.0)
      money (~> 6.12)
    money (6.13.1)
      i18n (>= 0.6.4, <= 2)
    money-rails (1.13.0)
      activesupport (>= 3.0)
      monetize (~> 1.9.0)
      money (~> 6.13.0)
      railties (>= 3.0)
    mono_logger (1.1.0)
    multi_json (1.13.1)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    mustermann (1.0.3)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (5.0.2)
    netrc (0.11.0)
    nilify_blanks (1.3.0)
      activerecord (>= 3.0.0)
      activesupport (>= 3.0.0)
    nio4r (2.3.1)
    nokogiri (1.8.5)
      mini_portile2 (~> 2.3.0)
    non-stupid-digest-assets (1.0.9)
      sprockets (>= 2.0)
    nprogress-rails (0.2.0.2)
    oauth2 (1.4.1)
      faraday (>= 0.8, < 0.16.0)
      jwt (>= 1.0, < 3.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.8.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-oauth2 (1.5.0)
      oauth2 (~> 1.1)
      omniauth (~> 1.2)
    originator (3.1)
      actionpack (>= 4.0)
      activerecord (>= 4.0)
    orm_adapter (0.5.0)
    overcommit (0.46.0)
      childprocess (~> 0.6, >= 0.6.3)
      iniparse (~> 1.4)
    parallel (1.12.1)
    parser (2.5.3.0)
      ast (~> 2.4.0)
    pdf-core (0.7.0)
    pg (0.20.0)
    pg_search (0.7.9)
      activerecord (>= 3.1)
      activesupport (>= 3.1)
      arel
    phantomjs (2.1.1.0)
    powerpack (0.1.2)
    prawn (2.2.2)
      pdf-core (~> 0.7.0)
      ttfunk (~> 1.5)
    prawn-svg (0.28.0)
      css_parser (~> 1.6)
      prawn (>= 0.11.1, < 3)
    prawn-table (0.2.2)
      prawn (>= 1.3.0, < 3.0.0)
    prawn_rails (0.0.11)
      prawn (>= 0.11.1)
      railties (>= 3.0.0)
    premailer (1.11.1)
      addressable
      css_parser (>= 1.6.0)
      htmlentities (>= 4.0.0)
    premailer-rails (1.10.2)
      actionmailer (>= 3, < 6)
      premailer (~> 1.7, >= 1.7.9)
    public_suffix (3.0.3)
    puma (3.12.0)
    rack (2.0.6)
    rack-attack (5.4.2)
      rack (>= 1.0, < 3)
    rack-cache (1.8.0)
      rack (>= 0.4)
    rack-protection (2.0.4)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rack-tracker (1.7.0)
      activesupport (>= 3.0)
      rack (>= 1.4)
      tilt (>= 1.4)
    rails (5.2.1)
      actioncable (= 5.2.1)
      actionmailer (= 5.2.1)
      actionpack (= 5.2.1)
      actionview (= 5.2.1)
      activejob (= 5.2.1)
      activemodel (= 5.2.1)
      activerecord (= 5.2.1)
      activestorage (= 5.2.1)
      activesupport (= 5.2.1)
      bundler (>= 1.3.0)
      railties (= 5.2.1)
      sprockets-rails (>= 2.0.0)
    rails-controller-testing (1.0.2)
      actionpack (~> 5.x, >= 5.0.1)
      actionview (~> 5.x, >= 5.0.1)
      activesupport (~> 5.x)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    rails-i18n (5.1.2)
      i18n (>= 0.7, < 2)
      railties (>= 5.0, < 6)
    rails_real_favicon (0.0.11)
      json (>= 1.7, < 3)
      rails (>= 3.1)
      rest-client (~> 2.0)
      rubyzip (~> 1)
    railties (5.2.1)
      actionpack (= 5.2.1)
      activesupport (= 5.2.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.19.0, < 2.0)
    rainbow (3.0.0)
    rake (12.3.1)
    ransack (2.1.0)
      actionpack (>= 5.0)
      activerecord (>= 5.0)
      activesupport (>= 5.0)
      i18n
    rb-fsevent (0.10.3)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    redcarpet (3.4.0)
    redis (4.0.3)
    redis-namespace (1.6.0)
      redis (>= 3.0.4)
    referer-parser (0.3.0)
    regexp_parser (1.3.0)
    request_store (1.4.1)
      rack (>= 1.4)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    resque (2.0.0)
      mono_logger (~> 1.0)
      multi_json (~> 1.0)
      redis-namespace (~> 1.6)
      sinatra (>= 0.9.2)
      vegas (~> 0.1.2)
    rest-client (2.0.2)
      http-cookie (>= 1.0.2, < 2.0)
      mime-types (>= 1.16, < 4.0)
      netrc (~> 0.8)
    rspec-core (3.8.0)
      rspec-support (~> 3.8.0)
    rspec-expectations (3.8.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-mocks (3.8.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-rails (3.8.1)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.8.0)
      rspec-expectations (~> 3.8.0)
      rspec-mocks (~> 3.8.0)
      rspec-support (~> 3.8.0)
    rspec-support (3.8.0)
    rubocop (0.60.0)
      jaro_winkler (~> 1.5.1)
      parallel (~> 1.10)
      parser (>= 2.5, != 2.5.1.1)
      powerpack (~> 0.1)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.4.0)
    rubocop-rspec (1.30.1)
      rubocop (>= 0.60.0)
    ruby-progressbar (1.10.0)
    ruby_dep (1.5.0)
    rubyzip (1.2.2)
    safe_yaml (1.0.4)
    safely_block (0.2.1)
      errbase
    sassc (2.0.0)
      ffi (~> 1.9.6)
      rake
    sassc-rails (2.0.0)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    select2-rails (3.5.10)
      thor (~> 0.14)
    shoulda-matchers (3.1.2)
      activesupport (>= 4.0.0)
    simple_form (4.1.0)
      actionpack (>= 5.0)
      activemodel (>= 5.0)
    simplecov (0.16.1)
      docile (~> 1.1)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)
    sinatra (2.0.4)
      mustermann (~> 1.0)
      rack (~> 2.0)
      rack-protection (= 2.0.4)
      tilt (~> 2.0)
    sixarm_ruby_unaccent (1.2.0)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-commands-rspec (1.0.4)
      spring (>= 0.9.1)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sshkit (1.18.0)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)
    terminal-table (1.8.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    thor (0.20.3)
    thread_safe (0.3.6)
    tilt (2.0.8)
    tiny_tds (0.7.0)
      mini_portile (= 0.6.2)
    ttfunk (1.5.1)
    turbolinks (5.2.0)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (4.1.13)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.5)
    unicode-display_width (1.4.0)
    unicode_utils (1.4.0)
    uniform_notifier (1.12.1)
    user_agent_parser (2.5.0)
    valid_email (0.1.2)
      activemodel
      mail (>= 2.6.1)
    vegas (0.1.11)
      rack (>= 1.0.0)
    warden (1.2.8)
      rack (>= 2.0.6)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    webmock (3.4.2)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
    websocket-driver (0.7.0)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)
    xpath (3.2.0)
      nokogiri (~> 1.8)

PLATFORMS
  ruby

DEPENDENCIES
  activerecord-session_store
  ahoy_email
  ahoy_matey (~> 2)
  alchemy-pg_search!
  alchemy_cms!
  autoprefixer-rails
  base58
  brakeman
  bullet
  byebug
  cancancan
  capistrano-rails
  capistrano-rbenv
  capistrano-yarn
  capistrano3-puma
  capybara
  capybara-screenshot
  countries
  dalli
  devise
  devise-i18n
  factory_bot_rails
  faker
  foundation_emails
  geocoder
  i18n-js (~> 3.2.0)
  i18n-tasks
  inky-rb
  inline_svg
  jbuilder (~> 2.5)
  letter_opener
  listen (>= 3.0.5, < 3.2)
  maxminddb
  mimemagic
  mini_racer
  money-rails
  nilify_blanks
  nokogiri
  nprogress-rails
  omniauth-oauth2
  overcommit
  pg (~> 0.20.0)
  phantomjs
  prawn (~> 2.2.0)
  prawn-svg
  prawn-table
  prawn_rails
  premailer-rails
  puma (~> 3.7)
  rack-attack
  rack-cache
  rack-tracker
  rails (~> 5.2.0)
  rails-controller-testing
  rails-i18n (~> 5.1)
  rails_real_favicon
  rainbow
  redcarpet
  resque
  rspec-rails
  rubocop
  rubocop-rspec
  sassc-rails
  shoulda-matchers (~> 3.1)
  simple_form
  simplecov
  spring
  spring-commands-rspec
  spring-watcher-listen (~> 2.0.0)
  tiny_tds (~> 0.7.0)
  uglifier (= 4.1.13)
  valid_email
  web-console (>= 3.3.0)
  webmock
  wice_grid!

RUBY VERSION
   ruby 2.5.1p57

BUNDLED WITH
   1.17.1
```

**Comment by PikachuEXE** [comment] 2018-11-28 02:18
It should be already fixed by #402 
We need more details to know if your issue is the same as this one

**Comment by afdev82** [comment] 2018-11-29 09:39
It works, probably I didn't wait enough time after the server was started. I get another error, but the files are generated.

**Comment by afdev82** [comment] 2018-11-29 10:01
If I delete the files manually, they are not generated anymore after a server restart, I don't know why... I tried also to clean the tmp folder

**Comment by afdev82** [comment] 2018-11-29 10:44
I tested more deeply and it seems that it works always if I make a request to the server. So it was probably my misunderstanding that it should generate the file when I start the server.
Anyway I read the comments before and [this issue](https://github.com/fnando/i18n-js/issues/394), it seems that it runs every time I make a request, this in production is not good. What is the status on that? My final goal is to have the files available for the browser and for a server side script.

I don't find the PR for the `ignore_middleware_cache` config option (see https://github.com/fnando/i18n-js/issues/350#issuecomment-209227343) or another that should fix this issue.

**Comment by afdev82** [comment] 2018-11-30 08:03
My final goal was to have the translations.js available also for a server side script, because I need it to execute the js server side (eg. with mini_racer).
I don't know how to get this file (and the i18n.js file), since they are in the gem and not in my project.
So the idea was to export the translations.js and use it in both the browser and with the server side script.

**Closed** 2021-05-25 16:46 UTC
Labels: kind/bug
