### ISSUE TITLE
How to use toNumber but leave precision untouched?

### ISSUE THREAD

**Issue by blueberry6401** [fnando/i18n-js#580] opened 2020-08-27 04:00 UTC
Hi,
I want to use toNumber, but leave the precision based on the input. For example: 1000.005 => 1,000.005; and 1000.00005 => 1,000.00005.
One way I can think is raise precision to big enough, and set strip_insignificant_zeros to true, but it leads to incorrect result:
```
 I18n.toNumber(10.005, {precision: 18, strip_insignificant_zeros: true})
Got '10.005000000000000782'
```
Is there any easy way to do this? Thank.

**Comment by PikachuEXE** [comment] 2020-08-27 06:11
This is caused by this library's `toFixed`
I am not experienced with JS float number handling
Do you have any idea on how to handle this? (Example from other libraries?)

**Comment by fnando** [comment] 2021-05-25 17:05
[v4](https://github.com/fnando/i18n-js/discussions/609) now uses [bignumber.js](https://npmjs.com/package/bignumber.js) to avoid precision errors like this. Closing it for now.

**Closed by fnando** 2021-05-25 17:05 UTC
