### ISSUE TITLE
NoMethodError: undefined method `merge' for nil:NilClass

### ISSUE THREAD

**Issue by DmitryKK** [fnando/i18n-js#337] opened 2015-06-17 08:29 UTC
Hello.

When i run `rake i18n:js:export` i get this error:

```
NoMethodError: undefined method `merge' for nil:NilClass
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js/utils.rb:18:in `deep_merge'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js.rb:68:in `block (2 levels) in merge_with_fallbacks!'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js/fallback_locales.rb:12:in `block in each'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js/fallback_locales.rb:12:in `each'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js/fallback_locales.rb:12:in `each'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js.rb:67:in `block in merge_with_fallbacks!'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js.rb:65:in `each'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js.rb:65:in `merge_with_fallbacks!'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js.rb:55:in `block in configured_segments'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js.rb:46:in `each'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js.rb:46:in `inject'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js.rb:46:in `configured_segments'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js.rb:85:in `translation_segments'
/Users/dmitrij/.rvm/gems/ruby-2.2.2@app/gems/i18n-js-3.0.0.rc10/lib/i18n/js.rb:34:in `export'
```

My config:

Rails: 4.2.0
I18n-js: 3.0.0.rc10

**Comment by PikachuEXE** [comment] 2015-06-17 08:41
Should be a duplicate of #334 ?

**Comment by barcala** [comment] 2015-06-17 08:51
I have the same problem. If I put inside my `i18n-js.yml` the following:
```
translations:
- file: "app/assets/javascripts/i18n/translations.js"
```
`rake i18n:js:export` command works fine, but if I put:
```
translations:
- file: "app/assets/javascripts/i18n/translations_en.js"
  only: "en.*"
- file: "app/assets/javascripts/i18n/translations_es.js"
  only: "es.*"
```
I get the same error.

**Comment by PikachuEXE** [comment] 2015-06-17 09:01
Thanks for providing detail
I will try to fix and release within this week ~_~ (busy interviewing though :S)

**Comment by PikachuEXE** [comment] 2015-06-18 07:18
Please use `master` to see if issue fixed

**Comment by barcala** [comment] 2015-06-18 11:12
It seems to be working fine now. Did you modify 3.0.0.rc10 also? It seems it's working fine with rc10 now (or I'm doing something wrong when changing releases inside bundler).

**Comment by PikachuEXE** [comment] 2015-06-18 12:47
The condition to trigger the bug is:
- Enable fallback
- The fallback locale has no translation

I only modify master, I **never** modify released stuff

**Comment by barcala** [comment] 2015-06-18 13:56
What I imagined. So, my example is working now with master release, but I'll try to reproduce the error in 3.0.0.rc10 again . I'm interested to know why bundler does not get rc10 release now.

**Comment by PikachuEXE** [comment] 2015-06-18 14:48
Need to specify the version exactly?
https://rubygems.org/gems/i18n-js/versions/3.0.0.rc10

**Comment by barcala** [comment] 2015-06-19 09:03
To sum up, the following works fine to return to `3.0.0.rc10`:
```
gem 'i18n-js', '3.0.0.rc10'
gem 'i18n-js', :git => 'https://github.com/fnando/i18n-js.git', :branch => 'v3.0.0.rc10'
```
(note the v letter necessary in the second line)

And the following doesn't work:
```
gem 'i18n-js', '3.0.0.rc10', :git => 'https://github.com/fnando/i18n-js.git'
gem 'i18n-js', 'v3.0.0.rc10', :git => 'https://github.com/fnando/i18n-js.git'
```
The first expression keep master version of git repository working on bundler and the second one raise an error. The first one can be a bundler bug of `1.10.0.pre.2` version, because `Gemfile.lock` points to `3.0.0.rc10` release of `i18n-js` but error related to this error is not raised. So I think bundler is using the `master` release of `i18n-js`.

**Comment by PikachuEXE** [comment] 2015-06-19 09:06
Check Gemfile.lock
if it said it's using `3.0.0.rc10` then it's doing something wrong

`bundler` is `1.10.4` now!

**Comment by barcala** [comment] 2015-06-19 09:24
I know, I know. But I make updates very carefully. I have made the same tests now with bundler 1.10.4 and problem persists. This expression:
```
gem 'i18n-js', '3.0.0.rc10', :git => 'https://github.com/fnando/i18n-js.git'
```
Causes this Gemfile.lock entries:
```
GIT
  remote: https://github.com/fnando/i18n-js.git
  revision: 3cabac6c29c82122e343cbf63f1003c99dd6adfc
  specs:
    i18n-js (3.0.0.rc10)
      i18n (~> 0.6)
...
DEPENDENCIES
  ...
  i18n-js (= 3.0.0.rc10)!
  ...
BUNDLED WITH
   1.10.4
```
I think it can be a bundler problem. Anyway, I have alternatives to specify the same and I'll use master branch until next i18n-js release.

Thank you.

**Comment by PikachuEXE** [comment] 2015-06-19 09:26
Remember, the master is also `3.0.0.rc10` but it should be `3.0.0.rc11-dev` (to be precise)
Don't trust the version number if you are using git repo as dependency

**Comment by PikachuEXE** [comment] 2015-06-19 09:27
See what it states `i18n-js (= 3.0.0.rc10)!`? The `!` means there might be some changes between actual released `3.0.0.rc10` and the one you are getting (unreleased)

**Comment by barcala** [comment] 2015-06-19 09:45
Ah, ok! So, is it not possible to indicate git release in bundler in this way, is it?
```
gem 'i18n-js', '3.0.0.rc10', :git => 'https://github.com/fnando/i18n-js.git'
```
And the correct expression must be?
```
gem 'i18n-js', :git => 'https://github.com/fnando/i18n-js.git', :branch => 'v3.0.0.rc10'
```
But with the second expression I get in Gemfile.lock:
```
GIT
  remote: https://github.com/fnando/i18n-js.git
  revision: 8317a393729167f850d886d2edd92375db73069c
  branch: v3.0.0.rc10
  specs:
    i18n-js (3.0.0.rc10)
      i18n (~> 0.6)
DEPENDENCIES
  ...
  i18n-js!
  ...
```
So, I don't know if I'm getting what I believed (again the !)

Many thanks for all your explanations.

**Comment by barcala** [comment] 2015-06-19 09:47
Is it possible to specify a branch or release name when get gems from git?

**Comment by barcala** [comment] 2015-06-19 10:18
From bundler doc:

Specify that a git repository should use a particular ref, branch, or tag
```
:git => 'https://github.com/rails/rails.git', :ref => '4aded'
:git => 'https://github.com/rails/rails.git', :branch => '2-3-stable'
:git => 'https://github.com/rails/rails.git', :tag => 'v2.3.5'
```
Specifying a ref, branch, or tag for a git repository specified inline works exactly the same way
```
gem 'nokogiri', :git => 'https://github.com/tenderlove/nokogiri.git', :ref => '0eec4'
```

**Comment by barcala** [comment] 2015-06-19 10:26
So, I think:
```
gem 'i18n-js', :git => 'https://github.com/fnando/i18n-js.git', :branch => 'v3.0.0.rc10'
```
or
```
gem 'i18n-js', :git => 'https://github.com/fnando/i18n-js.git', :tag => 'v3.0.0.rc10'
```
will use 3.0.0.rc10 release, even when the ! character appears on dependencies (in both cases).

Thank you again. Master release have solved the subject problem for me, so you can close this issue if you want :)

**Comment by PikachuEXE** [comment] 2015-06-19 22:10
Great!
Just don't know why you cannot get the released version (without option `git`)

**Closed by PikachuEXE** 2015-06-19 22:10 UTC
Labels: kind/bug
